{% set name = "funcx-common" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/funcx-common-{{ version }}.tar.gz
  sha256: ab998777dfaf4d414a422cb19ac7dc75ffa9906435cbcdf0ec4260b5817b4f8b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pydantic >=1,<2
    - moto <4
    - redis-py >=3.5.3,<5
    - boto3 >=1.19.0

test:
  imports:
    - funcx_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcX-faas/funcx-common
  summary: A common core repo for tools shared across multiple funcx python projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
